//! The knowledge schema deliberately lives apart from the legacy graph DB.

pub const SCHEMA_VERSION: i32 = 1;

pub const SCHEMA_SQL: &str = r#"
CREATE TABLE pages (page_id TEXT PRIMARY KEY, page_path TEXT NOT NULL UNIQUE, title TEXT NOT NULL, page_type TEXT NOT NULL, summary TEXT, primary_entity_id TEXT REFERENCES entities(entity_id), updated_at TEXT NOT NULL);
CREATE TABLE sections (section_id TEXT PRIMARY KEY, page_id TEXT NOT NULL REFERENCES pages(page_id) ON DELETE CASCADE, parent_id TEXT REFERENCES sections(section_id) ON DELETE CASCADE, heading_level INTEGER NOT NULL, heading_text TEXT NOT NULL, section_type TEXT NOT NULL, ui_scope TEXT, ui_anchor TEXT, ui_layer TEXT, ui_aspect TEXT, content_entity_id TEXT REFERENCES entities(entity_id), host_entity_id TEXT REFERENCES entities(entity_id), ordinal INTEGER NOT NULL, summary TEXT, UNIQUE(page_id, section_id));
CREATE TABLE entities (entity_id TEXT PRIMARY KEY, canonical_name TEXT NOT NULL, entity_type TEXT NOT NULL, description TEXT);
CREATE TABLE entity_aliases (entity_id TEXT NOT NULL REFERENCES entities(entity_id) ON DELETE CASCADE, alias TEXT NOT NULL, normalized_alias TEXT NOT NULL UNIQUE, PRIMARY KEY(entity_id, normalized_alias));
CREATE TABLE graphs (graph_id TEXT PRIMARY KEY, graph_name TEXT NOT NULL UNIQUE, purpose TEXT NOT NULL);
CREATE TABLE relation_types (graph_id TEXT NOT NULL REFERENCES graphs(graph_id) ON DELETE CASCADE, name TEXT NOT NULL, description TEXT NOT NULL, subject_types TEXT NOT NULL, object_types TEXT NOT NULL, inverse_name TEXT, symmetric INTEGER NOT NULL DEFAULT 0 CHECK(symmetric IN (0, 1)), object_cardinality TEXT NOT NULL CHECK(object_cardinality IN ('one', 'many')), PRIMARY KEY(graph_id, name));
CREATE TABLE graph_nodes (node_id TEXT PRIMARY KEY, graph_id TEXT NOT NULL REFERENCES graphs(graph_id) ON DELETE CASCADE, entity_id TEXT NOT NULL REFERENCES entities(entity_id), role TEXT, UNIQUE(graph_id, entity_id, role));
CREATE TABLE assertions (assertion_id TEXT PRIMARY KEY, graph_id TEXT NOT NULL REFERENCES graphs(graph_id) ON DELETE CASCADE, subject_entity_id TEXT NOT NULL REFERENCES entities(entity_id), predicate TEXT NOT NULL, object_entity_id TEXT NOT NULL REFERENCES entities(entity_id), origin TEXT NOT NULL CHECK(origin IN ('ingest', 'manual')), status TEXT NOT NULL CHECK(status IN ('active', 'review', 'superseded')), created_at TEXT NOT NULL, FOREIGN KEY(graph_id, predicate) REFERENCES relation_types(graph_id, name));
CREATE TABLE assertion_evidence (evidence_id TEXT PRIMARY KEY, assertion_id TEXT NOT NULL REFERENCES assertions(assertion_id) ON DELETE CASCADE, page_id TEXT REFERENCES pages(page_id) ON DELETE SET NULL, section_id TEXT REFERENCES sections(section_id) ON DELETE SET NULL, evidence_type TEXT NOT NULL CHECK(evidence_type IN ('supports', 'contradicts', 'mentions')), quote TEXT, confidence REAL, UNIQUE(assertion_id, section_id, evidence_type));
CREATE TABLE page_entities (page_id TEXT NOT NULL REFERENCES pages(page_id) ON DELETE CASCADE, section_id TEXT REFERENCES sections(section_id) ON DELETE CASCADE, entity_id TEXT NOT NULL REFERENCES entities(entity_id), role TEXT NOT NULL CHECK(role IN ('subject', 'mentions', 'ui_target', 'content_target')), PRIMARY KEY(page_id, section_id, entity_id, role));
CREATE TABLE tags (tag_id TEXT PRIMARY KEY, namespace TEXT NOT NULL, value TEXT NOT NULL, UNIQUE(namespace, value));
CREATE TABLE page_tags (page_id TEXT NOT NULL REFERENCES pages(page_id) ON DELETE CASCADE, tag_id TEXT NOT NULL REFERENCES tags(tag_id), PRIMARY KEY(page_id, tag_id));
CREATE INDEX idx_sections_page ON sections(page_id, ordinal); CREATE INDEX idx_nodes_entity ON graph_nodes(entity_id, graph_id); CREATE INDEX idx_assertions_graph ON assertions(graph_id); CREATE INDEX idx_assertions_subject ON assertions(subject_entity_id); CREATE INDEX idx_assertions_object ON assertions(object_entity_id); CREATE INDEX idx_evidence_page ON assertion_evidence(page_id); CREATE INDEX idx_evidence_section ON assertion_evidence(section_id); CREATE INDEX idx_evidence_assertion ON assertion_evidence(assertion_id); CREATE INDEX idx_page_entities_entity ON page_entities(entity_id, page_id); CREATE INDEX idx_pages_type ON pages(page_type); CREATE INDEX idx_sections_type ON sections(section_type); CREATE INDEX idx_relation_types_graph ON relation_types(graph_id, name); CREATE INDEX idx_page_tags_tag ON page_tags(tag_id, page_id);
"#;
